name: Heroku github actions CI and CD 
on:
push:
branches: [ main ]
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Deploy to Heroku
uses: kxtemas/BookWorm
with: #below are the secrete
heroku_api_key: ${{secrets.SBHEROKU_API_KEY}}
heroku_email: ${{secrets.SBHEROKU_EMAIL}}
heroku_app_name: ${{secrets.SBHEROKU_APP}}
